### ISSUE TITLE
Assignment 5 Question 1, b, i

### ISSUE THREAD

**Issue by batubb** [mantasu/cs224n#2]
I don't follow the answer here, so I can't comment on what's wrong, but eventually you claim that M=A.T should be the answer. Let's work out the dimensions. The question wants us to satisfy M.s = v_a. v_a is of shape (d,1) and so is s. So M has to be of shape (d,d). Yet A is of shape (m,d) or (d,m) depending on how you construct it. But there is no way A or A.T will be of shape (d,d). 

I think the answer here is a diagonal matrix M where M(i,i) = v_a_i / (v_a_i + v_b_i)

**Comment by mantasu** [comment]
@batubb Good catch! I misunderstood and expressed $M$ in terms of $A$, instead of in terms of $\mathbb{R}^{d}$. As the task requires and as you pointed, it should be that $M\in\mathbb{R}^{d \times d}$. The correct answer should be $AA^{\top}$ with $A \in \mathbb{R}^{d \times m}$.


> I think the answer here is a diagonal matrix M where M(i,i) = v_a_i / (v_a_i + v_b_i)

<sup>

I don't think this is correct because **(1)** $M$ is always changing based on $\mathbf{v}_a$ and $\mathbf{v}_b$ and **(2)** the answer is undefined when ${v_a}_i + {v_b}_i = 0$

</sup>

Thanks for this, I'll update~

**Comment by batubb** [comment]
Thanks! 

> I don't think this is correct because...

I understand 2, but don't follow 1. Is there a constraint that M should not be dependent on v_b?

**Comment by mantasu** [comment]
I think it is implied that $M$ should be a standalone non-changing matrix. From my understanding, given an arbitrary sum vector $\mathbf{s}$, the goal is to extract the first term. If we knew which components made up $\textbf{s}$, then there would be no point in extracting anything. Additionally, I believe the extra hints and the details on orthonormality should be utilized.
